config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists do
    resources :tasks, only: [:create, :new, :edit, :update, :destroy] do
      member do
        patch 'completeness'
      end
    end
  end
  root to: 'home#index' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :tasks, dependent: :destroy
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        if user_signed_in?
            redirect_to lists_path
        end
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @tasks = @list.tasks.where(completeness: true)
    @tasks_incomplete = @list.tasks.where(completeness: false)
  end

  # GET /lists/new
  def new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.build(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = current_user.lists.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_list, except: [:destroy, :edit, :update]
  before_action :set_task, only: [:edit, :update, :destroy, :completeness]


  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params.merge({list_id: params[:list_id]}))

    respond_to do |format|
      if @task.save 
        format.html { redirect_to list_path({id: @list.id}), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to list_url(id: @task.list_id), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to list_url(id: @task.list_id), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH /lists/1/tasks/2/completeness
  def completeness
    task_completeness = @task.completeness
    @task.update(completeness: !task_completeness)
    message_notice = 
      if @task.completeness == true 
        {notice: "You have done it!"}
      else
        {notice: "Task is not completed"}
      end
    redirect_to(list_url(id: @task.list_id), message_notice)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def load_list
      @list = List.find params[:list_id]
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<p style="text-align:center">Welcome to our TodoList! Here you can create your lists of plans and tasks to them.
  We hope you will be productive with our app :) </p>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>


<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Completeness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks_incomplete.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.completeness %></td>
        <td><%= link_to 'Done', completeness_list_task_path(list_id: @list.id, id: task.id), method: :patch %>
        <td><%= link_to 'Edit', edit_list_task_path(list_id: @list.id, id: task.id) %></td>
        <td><%= link_to 'Destroy', list_task_path(list_id: @list.id, id: task.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Completeness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.completeness %></td>
        <td><%= link_to 'Undone', completeness_list_task_path(list_id: @list.id, id: task.id), method: :patch %>
        <td><%= link_to 'Edit', edit_list_task_path(list_id: @list.id, id: task.id) %></td>
        <td><%= link_to 'Destroy', list_task_path(list_id: @list.id, id: task.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Task', new_list_task_path(@list.id) %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true, url: url) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task, url: list_task_path(list_id: @task.list_id, id: @task.id) %>

<%= link_to 'Back', list_path(id: @task.list_id) %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task, url: list_tasks_path(list_id: @list.id) %>

<%= link_to 'Back', list_tasks_path %>